// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Para migraciones conviene una conexión directa (sin pooler). La
    // integración de Neon en Vercel expone DATABASE_URL_UNPOOLED /
    // POSTGRES_URL_NON_POOLING; si no existen, se usa DATABASE_URL.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["DATABASE_URL"],
  },
});
